development:
  adapter: postgresql
  encoding: unicode
  database: ecid
  pool: 5
  username: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: seqapps
  pool: 5
  username: postgres
  password: Avaya123
