development:
  adapter: postgresql
  encoding: unicode
  database: ecid
  pool: 5
  username: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: postgres
  password:


